### ISSUE TITLE
bdist_rpm doesn't work

### ISSUE THREAD

**Issue by tlatorre-uchicago** [redis/hiredis-py#39]
I tried creating an RPM and installing it on CentOS 6, but I am getting the following error after installing:

```
>>> import hiredis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "hiredis/__init__.py", line 1, in <module>
    from .hiredis import Reader, HiredisError, ProtocolError, ReplyError
ImportError: No module named hiredis
```

Steps to reproduce:

```bash
$ git clone https://github.com/redis/hiredis-py
$ cd hiredis-py
$ git submodule update --init --recursive
$ python setup.py bdist_rpm
$ rpm -ivh dist/hiredis-0.2.0-1.x86_64.rpm
```

The version of python is 2.6.6 and setuptools 0.6.

**Comment by tlatorre-uchicago** [comment]
Oddly, if I build the package from the spec file it generates it does work, i.e.

```bash
$ mv build/bdist.linux-x86_64/rpm ~/rpmbuild
$ cd ~/rpmbuild/SPECS
$ rpmbuild -ba hiredis.spec
$ rpm -ivh ../RPMS/x86_64/hiredis-0.2.0-1.x86_64.rpm
```

Then it works! So, maybe this is a setuptools problem?

**Comment by ifduyue** [comment]
@tlatorre-uchicago Is this still a problem?

I can't replicate this in a centos:6 container.

```bash
yum install -y python-devel gcc git rpm-build
git clone --recursive https://github.com/redis/hiredis-py.git
cd hiredis-py
python setup.py bdist_rpm
rpm -ivh dist/hiredis-0.2.0-1.x86_64.rpm
cd /tmp
python
```

Notice that you need to cd to another directory, otherwise local folder hiredis will shadow the global one.
