### ISSUE TITLE
UnicodeDecodeError in setup.py

### ISSUE THREAD

**Issue by AndreyMZ** [redis/hiredis-py#91]
## Problem description
Cannot install hiredis on Windows.

## Steps to reproduce
1. Install [Python](https://www.python.org/downloads/windows/)
2. Run:
~~~bat
py -3.8 -m pip install hiredis
~~~

### Actual result
~~~
C:\>py -3.8 -m pip install hiredis
Collecting hiredis
  Using cached https://files.pythonhosted.org/packages/9e/e0/c160dbdff032ffe68e4b3c576cba3db22d8ceffc9513ae63368296d1bcc8/hiredis-1.0.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-rrjljd7j\\hiredis\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-rrjljd7j\\hiredis\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-install-rrjljd7j\hiredis\pip-egg-info'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-rrjljd7j\hiredis\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-rrjljd7j\hiredis\setup.py", line 22, in <module>
        long_description=open('README.md', 'r').read(),
      File "C:\Python38\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 2251: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
~~~

### Expected result
No errors.

## Additional information
hiredis 1.0.0, 0.3.1, 0.3.0 are affected. hiredis 0.2.0 is not affected.

**Comment by ifduyue** [comment]
Latest commit fixed this, could you try master and see if it works?

``pip install -e git+https://github.com/redis/hiredis-py@master#egg=hiredis``

**Comment by AndreyMZ** [comment]
It works:
~~~
C:\Users\user\Desktop>pip install -e git+https://github.com/redis/hiredis-py@master#egg=hiredis
Obtaining hiredis from git+https://github.com/redis/hiredis-py@master#egg=hiredis
  Cloning https://github.com/redis/hiredis-py (to revision master) to c:\users\user\desktop\src\hiredis
  Running command git clone -q https://github.com/redis/hiredis-py 'C:\Users\user\Desktop\src\hiredis'
  Running command git submodule update --init --recursive -q
Installing collected packages: hiredis
  Running setup.py develop for hiredis
Successfully installed hiredis
~~~
Waiting for the release on PyPI. Thank you!

**Comment by ifduyue** [comment]
v1.0.1 released
